### ISSUE TITLE
Error in file when running example code.

### ISSUE THREAD

**Issue by tomrutherford-livestyled** [GBSEcom/Python#2]
Getting the following error when running the code in the example from the REAE

`Traceback (most recent call last):
  File "main.py", line 6, in <module>
    import simple
  File "/GBSEcom/venv/lib/python3.8/site-packages/simple/__init__.py", line 2, in <module>
    from simple.gateway import Gateway
  File "/GBSEcom/venv/lib/python3.8/site-packages/simple/gateway.py", line 25
    self.order_api = OrderApi()
`

Is this library ready to use or is it still in development?

**Comment by ericmargules** [comment]
@tomrutherford-livestyled this SDK is the product of a code generator, though it has been tested and should work with the sample code. Have you made any progress on your error?

**Comment by dobosevych** [comment]
I have the same issue with my `Python 3.10.6`
Way to reproduce
`from simple import Gateway`
